name: Unity Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: actions/cache@v1.1.0
        with:
          path: ~/.nuget/packages

      - name: Install NUnit
        run: |
          dotnet new tool-manifest
          dotnet tool install nunit.console --tool-path ./.nuget
          export PATH="$PATH:$(pwd)/.nuget"

      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}

      - name: Run Unit Tests
        run: |
          nunit3-console Library/ScriptAssemblies/Tests.dll
